### ISSUE TITLE
Does this method gurantee ergodicity?

### ISSUE THREAD

**Issue by Char-Aznable** [ermongroup/a-nice-mc#8]
First of all, very nice work! @jiamings  I'm not sure where to ask this question so I'm posting it here. My main concern is that feed forward neural networks are bad at extrapolation. Could fitting the proposal distribution to certain samples, e.g. the bootstrapped samples described in the paper, hampers ergodicity?

**Comment by jiamings** [comment]
That is a good question. Because we use the additional random variable `v` in addition to `x`, and the fact that NICE is volume preserving, I think ergodicity over the space for `(x, v)` is not a problem **in theory**. 

In practice, the fact that we start from random network helps us with relatively low dimensional problem, but becomes an issue when the dimension of the problem is larger. Nevertheless, exploration is a problem for MCMC in general, and not specific to our method.

**Comment by Char-Aznable** [comment]
Let's focus on the theoretical gurantee. There are examples of dynamic systems that are conditionally ergodic depending on the auxillary variables, for example, the Nose-Hoover chain. In these systems, there are invariant subspaces of (x,v) under the transition operator, i.e., there is no transition possible outside of a invariant subspace if the chain started within it. I was just wondering if your method can guarantee that no such invariant subspaces exist. In another word, is the markov chain irreducible in this method? especially for those part of (x,v) that is not exposed in the training of the network. Note that volume preserving is an orthogonal property to this because you can map (x,v) onto itself preserving the volume but just different subspaces can only map back to themselves. 

Thank you for your reply anyway! @jiamings

**Comment by jiamings** [comment]
I see, that is a fair point! 

Then for some NICE network the chain might not be ergodic (say identity transformation), but I think everything should work out if you initialized properly. The objective itself also optimizes some form of auto-correlation.
